nelmio_cors:
    defaults:
        allow_credentials: false
        origin_regex: false
        allow_origin: []
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        forced_allow_origin_value: ~

    paths:
        '^/api/':
          allow_origin: ['*']
          allow_headers: ['Content-Type', 'Authorization','X-Custom-Auth']
          allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
          max_age: 3600

        '^/':
          origin_regex: true
          allow_origin: ['^http://localhost:[0-9]+']
          allow_headers: ['X-Custom-Auth']
          allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
          max_age: 3600
          hosts: ['^api\.']